### ISSUE TITLE
Native hash

### ISSUE THREAD

**Issue by TheMrCreator** [czastack/wxFEFactory#1]
Hello there. Sorry for create issue here. Could you explain how to get hative hashes from updated version of GTA? Thx u!

**Comment by czastack** [comment]
@TheMrCreator Is the new version of GTAV? See this: https://github.com/ivanmeler/OpenVHook/blob/master/OpenVHook/Scripting/ScriptEngine.cpp

My solution is from the OpenVHook. My tool is writing in python and call CreateRemoteThread in c++, without gtathread. And I use the ScriptHook Finally.

**Comment by TheMrCreator** [comment]
Thx u for reply! No, isn't new version yet. I'm just trying to undestend how to research new native hashes after update. But can't find some examples.

**Comment by czastack** [comment]
You can use the "ida pro" to open the GTA5.exe and find the native hash area by the old version GTA5.exe and hash. But in the newest version, the hash is not straightly store in GTA5.exe. And I am not very good at it also.

**Comment by TheMrCreator** [comment]
@czastack thx for you answers!
